import {NextResponse} from 'next/server';

export const dynamic='force-dynamic';

const MAX_AGE=36*60*60*1000;
const NITTER_BASES=['https://nitter.cf','https://xcancel.com'];
const SOURCES={
 juventusfc:'Juventus',tuttosport:'Tuttosport',gazzetta_it:'La Gazzetta dello Sport',corsport:'Corriere dello Sport',
 skysport:'Sky Sport',sportmediaset:'Sport Mediaset',dimarzio:'Gianluca Di Marzio',fabrizioromano:'Fabrizio Romano',
 nicoschira:'Nicolò Schira',romeoagresti:'Romeo Agresti',giovaalbanese:'Giovanni Albanese',alfredopedulla:'Alfredo Pedullà',
 cmdotcom:'Calciomercato.com',tuttomercatoweb:'Tuttomercatoweb',goalitalia:'Goal Italia',footballitalia:'Football Italia',
 glongari:'Gianluigi Longari',cronachetweet:'Cronache di Spogliatoio',calciofinanza:'Calcio e Finanza',
 mattemoretto:'Matteo Moretto',fbians:'Fabrizio Biasin',fbiasin:'Fabrizio Biasin',marcoconterio:'Marco Conterio',
 '86_longo':'Daniele Longo',nicolabalice:'Nicola Balice',filippocornacchia:'Filippo Cornacchia',fabdellavalle:'Fabiana Della Valle'
};
const HANDLES=Object.keys(SOURCES);
const JUVE='(Juventus OR Juve OR bianconeri OR Continassa)';

function decodeXml(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
function xmlText(block,tag){const m=block.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decodeXml(m[1].trim()):'';}
function clean(v=''){return decodeXml(v).replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/https?:\/\/(?:www\.)?(?:nitter\.cf|xcancel\.com)(?::\d+)?\/t\.co\/\S+/gi,'').replace(/https?:\/\/t\.co\/\S+/gi,'').replace(/\s+/g,' ').trim();}
function relevant(body=''){return /(?:\bjuventus\b|\bjuve\b|\bbianconer\w*\b|\bcontinassa\b|@juventusfc\b)/i.test(body)}
function parse(xml){const out=[];for(const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const b=m[1],raw=xmlText(b,'link')||xmlText(b,'guid');const hit=raw.match(/(?:x|twitter)\.com\/([A-Za-z0-9_]+)\/status\/(\d+)/i)||raw.match(/\/([A-Za-z0-9_]+)\/status\/(\d+)/i);if(!hit)continue;const handle=hit[1].toLowerCase(),source=SOURCES[handle];if(!source)continue;const date=xmlText(b,'pubDate')||xmlText(b,'dc:date'),ts=Date.parse(date)||0;if(!ts||Date.now()-ts>MAX_AGE)continue;const title=clean(xmlText(b,'title')),desc=clean(xmlText(b,'description')),body=[desc,title].sort((a,b)=>b.length-a.length)[0]||'';if(!body||!(handle==='juventusfc'||relevant(body)))continue;out.push({source,body,date,ts,link:`https://x.com/${hit[1]}/status/${hit[2]}`});}return out;}
async function fetchOfficialX(){const token=process.env.X_BEARER_TOKEN||process.env.TWITTER_BEARER_TOKEN;if(!token)return [];const groups=[];for(let i=0;i<HANDLES.length;i+=8)groups.push(HANDLES.slice(i,i+8));const jobs=groups.map(async g=>{const authors=g.map(h=>`from:${h}`).join(' OR '),q=`${JUVE} (${authors}) -is:retweet`;const url='https://api.x.com/2/tweets/search/recent?max_results=100&tweet.fields=created_at,author_id&expansions=author_id&user.fields=username&query='+encodeURIComponent(q);const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{Authorization:`Bearer ${token}`,Accept:'application/json'}});if(!r.ok)throw new Error('x_'+r.status);const data=await r.json(),users=new Map((data.includes?.users||[]).map(u=>[u.id,u]));return (data.data||[]).map(tweet=>{const u=users.get(tweet.author_id);if(!u)return null;const handle=String(u.username||'').toLowerCase(),source=SOURCES[handle],body=clean(tweet.text||''),date=tweet.created_at,ts=Date.parse(date)||0;if(!source||!body||!ts||Date.now()-ts>MAX_AGE)return null;return {source,body,date,ts,link:`https://x.com/${u.username}/status/${tweet.id}`};}).filter(Boolean);}finally{clearTimeout(t)}});const settled=await Promise.allSettled(jobs);return settled.flatMap(r=>r.status==='fulfilled'?r.value:[])}
async function fetchNitter(base,q){const c=new AbortController(),t=setTimeout(()=>c.abort(),4500);try{const r=await fetch(`${base}/search/rss?f=tweets&q=${encodeURIComponent(q)}`,{cache:'no-store',signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml,application/xml,text/xml;q=0.9,*/*;q=0.5'}});if(!r.ok)throw new Error(String(r.status));const xml=await r.text();if(!/<item>/i.test(xml))throw new Error('empty');return parse(xml);}finally{clearTimeout(t)}}
async function fetchBing(q){const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await fetch(`https://www.bing.com/search?format=rss&setlang=it-IT&cc=IT&q=${encodeURIComponent(q)}`,{cache:'no-store',signal:c.signal,headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml,text/xml;q=0.9,*/*;q=0.5'}});if(!r.ok)throw new Error(String(r.status));return parse(await r.text());}finally{clearTimeout(t)}}
function dedupe(a){const seen=new Set();return a.sort((x,y)=>y.ts-x.ts).filter(p=>{if(seen.has(p.link))return false;seen.add(p.link);return true})}
export async function GET(){try{const jobs=[fetchOfficialX()];for(const base of NITTER_BASES){jobs.push(fetchNitter(base,'Juventus'));jobs.push(fetchNitter(base,'Juve'));}for(const h of HANDLES)jobs.push(fetchBing(`site:x.com/${h}/status ${JUVE}`));const settled=await Promise.allSettled(jobs);const posts=dedupe(settled.flatMap(r=>r.status==='fulfilled'?r.value:[])).slice(0,300);const sources=[...new Set(posts.map(p=>p.source))];return NextResponse.json({posts,generatedAt:new Date().toISOString(),officialX:Boolean(process.env.X_BEARER_TOKEN||process.env.TWITTER_BEARER_TOKEN),sourceCount:sources.length},{headers:{'Cache-Control':'public, s-maxage=45, stale-while-revalidate=120'}})}catch{return NextResponse.json({posts:[],degraded:true},{headers:{'Cache-Control':'no-store'}})}}
