const articles=[
['Editoriali','Tuttosport','Incredibile sequenza di errori, vecchi spettri e nuove speranze','Guido Vaciago','La Juve ha sbagliato sette gol in un’ora e il problema della concretezza resta quello della scorsa stagione. Kolo Muani non è un bomber spietato e neppure Zirkzee sarebbe il centravanti d’area che cerca Spalletti: Carnevali e Massara devono evitare un altro equivoco di mercato. Restano segnali positivi da McKennie, Celik, Conceiçao, Bremer e Kalulu; Douglas Luiz dà qualità alla costruzione, mentre Kessié e Lucumì possono aggiungere dinamismo e uscita da dietro.','74',5],
['Editoriali','Corriere dello Sport','Primi segnali dallo spazio','Ivan Zazzaroni','Dopo aver contato pochissimi italiani titolari nelle prime partite, Zazzaroni trova nella giornata diversi segnali incoraggianti. Zaniolo, Palma, Mout, Pio Esposito, Alessandro Romano, Vergara, Cacciamani e Bernasconi mostrano che i giovani italiani, quando ricevono fiducia, possono incidere. La conclusione è che la giovinezza non può essere considerata un difetto: questi ragazzi devono giocare con continuità e avere anche il diritto di sbagliare.','126',3],
['Editoriali','La Gazzetta dello Sport','Milan, ringrazia i tenori. È sempre la stessa Juve, ora impari a dominare','Fabio Capello','La Juventus vista a Frosinone è, per Capello, sostanzialmente la stessa dello scorso anno: il pallone gira troppo lentamente e la squadra non riesce a dominare con continuità. Conceiçao è la nota più positiva, mentre i nuovi acquisti si sono visti poco. Le occasioni sono arrivate, ma contro un avversario che sembrava alla portata la Juve non è mai riuscita a prendere davvero in mano la partita e chiuderla rapidamente.','37',5],
['Editoriali','Corriere dello Sport','Non basta il lavoro di Lucio','Vittorio Oreggia','Il successo di Frosinone conferma in parte la qualità del lavoro di Spalletti: il 4-2-3-1 funziona, la Juve aggredisce le seconde palle, gestisce bene per un’ora e mostra elementi in crescita come Bremer, Conceiçao, Douglas Luiz e McKennie. Ma il mercato non può finire qui, soprattutto in attacco. Kolo Muani è più efficace nelle sponde che davanti alla porta e la mancanza di cinismo resta il grande limite: dieci occasioni per segnare un gol sono troppe.','19',4],
['Juventus','La Gazzetta dello Sport','Juve a metà. Vince ma rischia','', 'Una Juve “nuova vecchissima”: a tratti bella, poi sprecona e infine passiva e impaurita. Il primo tempo avrebbe potuto chiudersi con quattro gol di vantaggio, invece il solo gol di Bremer costringe i bianconeri a tremare fino alla traversa finale del Frosinone. Per Licari la partita manda anche un messaggio al mercato: servono ancora un regista, un terzino e un attaccante.','30',5],
['Juventus','Corriere della Sera','Juve, tornano i vecchi difetti. Vittoria col brivido finale. Spalletti: “Kolo, voglio i gol”','', 'La Juve domina il primo tempo ma spreca l’impossibile e nel recupero rischia il pari sulla traversa di Calvani. Spalletti striglia Kolo: «È due anni che non gioca e un motivo ci sarà» e chiarisce: «Queste son partite in cui c’è bisogno che porti a casa dei gol».','9',5],
['Juventus','La Gazzetta dello Sport','Spalletti: “Voglio un altro 9”','', 'Spalletti riconosce l’identità della Juve, ma ammette: «In alcuni momenti siamo stati troppo leggeri». Poi punge Kolo Muani: «Se è due anni che non gioca un motivo ci sarà». Sul nuovo attaccante: «Cerchiamo una punta diversa, perché ci sono partite in cui è più facile metterla di testa negli ultimi 20 minuti».','39',5],
['Juventus','La Stampa','Spalletti bacchetta Kolo e squadra: “Così siamo soltanto quasi forti”','', 'Spalletti insiste su Kolo: «Si deve rendere conto che è da due anni che non gioca e un motivo ci sarà» e gli imputa «due o tre» errori sotto porta. Poi allarga il discorso: «Siamo una squadra... quasi forte». Sul mercato aumentano il pressing per Zirkzee e i contatti per Sorloth, mentre Kessié è più vicino.','49',5],
['Juventus','La Repubblica','Vincere non basta, alta tensione alla Juve. Spalletti contro Kolo','', 'Spalletti attacca Kolo: «Ora Kolo è in debito e deve restituirci tutto». Sul mercato Zirkzee è il centravanti indicato dal tecnico, ma prima deve uscire David; stesso incastro a centrocampo, dove senza la partenza di Koopmeiners non si apre la strada a Kessié.','43',5],
['Mercato','Corriere dello Sport','Miretti verso il Besiktas. Ora Kessié','', 'Miretti è vicinissimo al Besiktas: si tratta su un prestito con diritto di riscatto e una valutazione intorno ai 10-12 milioni. La sua partenza avvicinerebbe Kessié, centrocampista di forza voluto da Spalletti come alternativa a Thuram.','18',4],
['Mercato','Tuttosport','Kessié ora fa il tifo per Miretti','', 'Dopo l’addio di Arthur, la cessione di Miretti aprirebbe lo spazio necessario per Kessié, considerato un upgrade tecnico, tattico e di personalità. Il Besiktas lo vuole su indicazione di Italiano.','68',4],
['Mercato','Tuttosport','Grabara scalda i guanti. Oggi Perin al Palermo','', 'Perin è pronto a lasciare definitivamente la Juve per il Palermo e firmare un biennale. Il sostituto più probabile è Grabara del Wolfsburg: con il portiere c’è un accordo di massima.','67',4],
['Juventus','Tuttosport','Douglas è il padrone, Conceiçao a metà','', 'Douglas Luiz prende 7: è intenso e concreto e «si vede la mano di Spalletti». Conceiçao è devastante sulla fascia e firma un assist splendido, ma spreca il raddoppio; bene anche Bremer e Kalulu.','65',3],
['Juventus','La Gazzetta dello Sport','Bremer lo specialista','', 'Bremer decide la gara con una delle sue specialità. «Il gol di testa è una delle mie specialità, da quando sono in Italia ci lavoro molto», spiega il brasiliano, che aggiunge: «Potevamo chiuderla prima. Dobbiamo lavorare tanto, anche per inserire i nuovi arrivati».','35',3],
['Juventus','La Gazzetta dello Sport','Palmisani ritarda il rinvio dal fondo: corner per la Juve','', 'Alla mezz’ora arriva la prima applicazione della regola dei cinque secondi: Palmisani tarda la rimessa dal fondo e Ayroldi assegna un corner alla Juventus. Partita senza episodi spinosi.','34',2],
['Mercato','Corriere dello Sport, ed. Bologna','Un rapporto da ricostruire per Cabal','', 'Il Bologna pensa a Cabal per sostituire Lucumì e deve riallacciare i rapporti dopo il precedente stop. La Juve può favorire l’uscita, anche perché a Torino il difensore rischierebbe poco spazio.','104',3],
['Next Gen','Corriere di Novara','Autogol e polemiche: la baby Juve rovina l’esordio del Novara','', 'La Next Gen vince 1-0 grazie all’autogol di Lorenzini dopo dodici minuti e gestisce a lungo il possesso. Il Novara recrimina per il gol di Basso prima convalidato e poi annullato.','79',3],
['Next Gen','Corriere di Novara','Brambilla: “L’unico cruccio è stato quello di non chiuderla”','', 'Brambilla sottolinea la buona gestione della Next Gen dopo il vantaggio: «Abbiamo tenuto bene la palla». Il rimpianto è uno solo: «L’unico cruccio è stato quello di non chiuderla, ma la vittoria è meritata».','82',3],
['Women','Eco di Biella','Juventus Women, esordio vincente a Como in A','', 'La Juventus Women di Isaac Guerrero debutta nella Serie A Women’s Cup con il 2-0 al Como firmato Redondo e Chiba. Mercoledì 26 agosto c’è l’andata del terzo turno contro il St. Pölten.','85',3],
['Politica sportiva','La Repubblica','Arbitri, meno fischi e più polemiche: il nuovo corso è già sotto accusa','', 'Orsato ha imposto un metro più vicino alla Premier: meno fischi sui contatti minimi, meno interruzioni e meno interventi VAR. Il caso De Bruyne-Vasquez in Genoa-Napoli accende subito le polemiche.','93',3],
['Altre squadre','La Repubblica','Un anno da Pio, la missione di Esposito tra Inter e azzurro','', 'Pio Esposito apre la stagione con un gol di tacco e un assist e dice di voler crescere «anche facendo il lavoro sporco per i compagni». È ormai considerato presente dell’Inter e della Nazionale.','95',2]];
const sources=['Tuttosport','La Gazzetta dello Sport','Corriere dello Sport','Corriere della Sera','La Stampa','La Repubblica','Corriere di Novara','Eco di Biella'];
const stars=n=>'★'.repeat(n)+'☆'.repeat(5-n);
export default function Page(){return <main><header><div className="top"><div className="brand"><i>JUMP</i> PRESS</div><div className="edition">JUVENTUS · DAILY MEDIA INTELLIGENCE</div></div><small>LUNEDÌ 24 AGOSTO 2026</small><h1>Rassegna stampa <em>Juventus</em></h1><p className="lead">La Juventus apre il campionato vincendo 1-0 a Frosinone con un gol di Bremer, ma il risultato non cancella i problemi emersi: i bianconeri creano molto, sprecano diverse occasioni e nel recupero rischiano il pareggio sulla traversa di Calvani. Spalletti critica soprattutto Kolo Muani e chiede maggiore concretezza, mentre dal mercato aspetta ancora un attaccante con caratteristiche diverse. Miretti si avvicina al Besiktas e la sua uscita può favorire l’arrivo di Kessié; Perin è verso Palermo e la Juve lavora per Grabara. Intanto iniziano con una vittoria anche la Next Gen e la Juventus Women, attesa ora dalla Champions.</p><div className="stats"><div><b>21</b><span>articoli selezionati</span></div><div><b>8</b><span>fonti analizzate</span></div><div><b>4</b><span>editoriali</span></div><div><b>5</b><span>temi ★★★★★</span></div></div></header>
<section className="brief"><small>EXECUTIVE BRIEF</small><h2>La lettura complessiva della giornata</h2><p className="intro">La vittoria all’esordio non produce una lettura pienamente rassicurante. Il tratto comune delle principali testate è la distanza fra volume di gioco e concretezza: la Juventus crea, ma non chiude la partita e finisce per esporsi al rischio del pareggio. Le parole di Spalletti su Kolo Muani amplificano il tema e trasformano l’attacco nel dossier dominante anche in chiave mercato. Parallelamente emergono segnali positivi individuali — Bremer, Conceiçao e Douglas Luiz — e arrivano risultati favorevoli da Next Gen e Women.</p><div className="briefgrid"><div className="hot"><b>TEMI CALDI</b><h3>Attacco e mercato al centro</h3><p>La richiesta di Spalletti per una punta diversa, il rendimento di Kolo Muani e i dossier Zirkzee e Sorloth concentrano l’attenzione. Miretti–Kessié e Perin–Grabara completano una giornata fortemente orientata al mercato.</p></div><div className="delicate"><b>TEMI DELICATI</b><h3>Concretezza e gestione del vantaggio</h3><p>Le occasioni sprecate e il finale in sofferenza sono il principale elemento critico. Le parole molto nette di Spalletti su Kolo Muani rendono il tema particolarmente sensibile sul piano tecnico e mediatico.</p></div><div className="positive"><b>NOTIZIE POSITIVE</b><h3>Bremer e segnali dalle altre squadre</h3><p>Bremer decide l’esordio; Conceiçao e Douglas Luiz raccolgono giudizi positivi. Vincono anche Next Gen e Juventus Women, offrendo un contrappeso alla lettura critica della prima squadra.</p></div></div></section>
<section className="ranking"><small>PRIORITÀ MEDIA</small><h2>Ranking delle notizie</h2><p>Valutazione editoriale interna da una a cinque stelle in base a rilevanza per Juventus, ricorrenza sulle testate e sensibilità del tema.</p><div className="rankrow"><strong>★★★★★</strong><span><b>Spalletti, Kolo Muani e richiesta di un altro 9</b><small>Tema dominante e trasversale sulle principali testate</small></span></div><div className="rankrow"><strong>★★★★★</strong><span><b>Vittoria con sprechi e rischio nel finale</b><small>La lettura tecnica più ricorrente dell’esordio</small></span></div><div className="rankrow"><strong>★★★★☆</strong><span><b>Miretti–Kessié e Perin–Grabara</b><small>Due incastri di mercato direttamente collegati alle prossime mosse</small></span></div><div className="rankrow"><strong>★★★☆☆</strong><span><b>Bremer, Conceiçao e Douglas Luiz</b><small>I principali segnali individuali positivi</small></span></div><div className="rankrow"><strong>★★★☆☆</strong><span><b>Next Gen e Juventus Women</b><small>Esordi vincenti e attenzione ai prossimi impegni</small></span></div></section>
<section className="sources"><small>FONTI ANALIZZATE</small><h2>Le testate della rassegna</h2><div>{sources.map(s=><span key={s}>{s}</span>)}</div></section>
<div className="sectiontitle"><small>RASSEGNA COMPLETA</small><h2>Tutti gli articoli selezionati</h2></div><section className="articles">{articles.map((a,i)=><article key={i}><div className="meta"><label><span>{a[0]}</span><b>{a[1]}</b></label><div className="stars" title={`${a[6]} stelle su 5`}>{stars(a[6])}</div></div><h2>{a[2]}</h2>{a[3]&&<aside>di {a[3]}</aside>}<p>{a[4]}</p><a href={`/ritagli/${a[5]}.pdf`} target="_blank" rel="noreferrer">Apri ritaglio completo <b>↗</b></a></article>)}</section><footer><b>JUMP PRESS</b> · Rassegna Juventus · 24 agosto 2026<br/><span>21 articoli · 8 fonti · ritagli originali consultabili</span></footer></main>}