import {unstable_cache} from 'next/cache';
import SocialRefresh from './SocialRefresh';
import SocialFeed from './SocialFeed';

export const dynamic='force-dynamic';
const SOCIAL_MAX_AGE=3*24*60*60*1000;
const X_FEED_BASES=[
 'https://rsshub.yfi.moe',
 'https://rsshub.stsecurity.moe',
 'https://rsshub.edwardcc.com',
 'https://rsshub.isrss.com',
 'https://rsshub.rssforever.com',
 'https://hub.slarker.me'
];
const SOCIAL_SOURCES=[
 {name:'Juventus',handle:'juventusfc',official:true},{name:'Gianluca Di Marzio',handle:'DiMarzio'},
 {name:'Fabrizio Romano',handle:'FabrizioRomano'},{name:'Nicolò Schira',handle:'NicoSchira'},
 {name:'Gianluigi Longari',handle:'Glongari'},{name:'Romeo Agresti',handle:'romeoagresti'},
 {name:'TUTTOmercatoWEB',handle:'TuttoMercatoWeb'},{name:'Cronache di Spogliatoio',handle:'CronacheTweet'},
 {name:'Corriere dello Sport',handle:'CorSport'},{name:'Sport Mediaset',handle:'sportmediaset'},
 {name:'Sky Sport',handle:'SkySport'},{name:'ilBiancoNero',handle:'ilbianconerocom'},
 {name:'Fanpage.it',handle:'fanpage'},{name:'Calcio Totale',handle:'calcio_morelli'},
 {name:'Calcio e Finanza',handle:'CalcioFinanza',allPosts:true},{name:'Paolo Ardoino',handle:'paoloardoino',ardoino:true}
];
function decodeXml(s=''){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)));}
function xmlText(block,tag){const m=block.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decodeXml(m[1].trim()):'';}
function cleanHtml(v=''){return decodeXml(v).replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/https?:\/\/t\.co\/\S+/gi,'').replace(/\s+/g,' ').trim();}
function relevantToJuve(body='',s={}){return /\b(juventus|juve|bianconer\w*|allianz\s*stadium|spalletti|yildiz|miretti|bremer|thuram|koopmeiners|cambiaso|vicario|di\s*gregorio|chiellini|comolli|kessi[eé]|sorloth|zirkzee|kolo\s*muani|david|muharemovi[cć]|martinez)\b/i.test(body)||Boolean(s.ardoino&&/\b(zebra|zebre|jay)\b/i.test(body));}
function parseXFeed(xml,s){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>{const b=m[1],date=xmlText(b,'pubDate')||xmlText(b,'dc:date'),title=cleanHtml(xmlText(b,'title')),desc=cleanHtml(xmlText(b,'description')),enc=cleanHtml(xmlText(b,'content:encoded'));let body=[enc,desc,title].sort((a,b)=>b.length-a.length)[0]||'';body=body.replace(/^RT by @?[^:]+:\s*/i,'').replace(/^RT @?[^:]+:\s*/i,'').trim();const raw=xmlText(b,'link')||xmlText(b,'guid'),status=raw.match(/\/status\/(\d+)/)?.[1];return {source:s.name,body,date,ts:Date.parse(date)||0,link:status?`https://x.com/${s.handle}/status/${status}`:`https://x.com/${s.handle}`};}).filter(p=>p.body&&(s.official||s.allPosts||relevantToJuve(p.body,s)));}
async function fetchRss(handle){let err;for(const base of X_FEED_BASES){const c=new AbortController(),t=setTimeout(()=>c.abort(),4500);try{const r=await fetch(`${base}/twitter/user/${handle}/exclude_replies`,{cache:'no-store',signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5'}});if(!r.ok)throw new Error(`${base} ${r.status}`);const xml=await r.text();if(!/<item>/i.test(xml))throw new Error(`${base} empty`);return xml;}catch(e){err=e}finally{clearTimeout(t)}}throw err||new Error('rss unavailable');}
function cleanMarkdown(s=''){return s.replace(/\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)/g,' ').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\\([#_*`])/g,'$1').replace(/## Log in or sign up for X[\s\S]*$/i,'').replace(/## See .*?full profile[\s\S]*$/i,'').replace(/\s+/g,' ').trim();}
function relativeDate(label=''){const now=Date.now();let m=label.match(/^(\d+)(s|m|h|d)$/i);if(m){const mult={s:1000,m:60000,h:3600000,d:86400000}[m[2].toLowerCase()];return new Date(now-Number(m[1])*mult)}m=label.match(/^([A-Z][a-z]{2})\s+(\d{1,2})(?:,\s*(\d{4}))?$/);if(m){const y=m[3]?Number(m[3]):new Date().getUTCFullYear();return new Date(`${m[1]} ${m[2]}, ${y} 12:00:00 UTC`)}return new Date(0)}
function parseJina(text,s){const out=[];for(const block of text.split(/\n(?=\*\s+)/g)){const re=new RegExp(`\\[([^\\]]+)\\]\\(https:\\/\\/x\\.com\\/${s.handle}\\/status\\/(\\d+)\\)`,'i'),hit=block.match(re);if(!hit)continue;const body=cleanMarkdown(block.slice((hit.index||0)+hit[0].length)),d=relativeDate(hit[1].trim()),ts=d.getTime();if(!body||!ts||!(s.official||s.allPosts||relevantToJuve(body,s)))continue;out.push({source:s.name,body,date:d.toISOString(),ts,link:`https://x.com/${s.handle}/status/${hit[2]}`});}return out;}
async function fetchJina(handle){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(`https://r.jina.ai/https://x.com/${handle}`,{cache:'no-store',signal:c.signal,headers:{Accept:'text/plain','User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(String(r.status));return await r.text();}finally{clearTimeout(t)}}
const cachedRss=unstable_cache(async h=>fetchRss(h),['jump-social-rsshub-v10'],{revalidate:180});
const cachedJina=unstable_cache(async h=>fetchJina(h),['jump-social-jina-fallback-v2'],{revalidate:300});
async function one(s){try{const posts=parseXFeed(await cachedRss(s.handle),s);if(posts.length)return posts.slice(0,s.allPosts?20:12);}catch{}try{return parseJina(await cachedJina(s.handle),s).slice(0,s.allPosts?20:8);}catch{return []}}
function dedupe(a){const seen=new Set();return a.sort((x,y)=>y.ts-x.ts).filter(p=>{const key=p.link||p.body.toLowerCase().replace(/\s+/g,' ').trim();if(!key||seen.has(key))return false;seen.add(key);return true})}
async function liveSocial(){const settled=await Promise.allSettled(SOCIAL_SOURCES.map(one));const cutoff=Date.now()-SOCIAL_MAX_AGE,counts=new Map();return dedupe(settled.flatMap(r=>r.status==='fulfilled'?r.value:[])).filter(p=>p.ts>=cutoff).filter(p=>{const max=p.source==='Calcio e Finanza'?20:p.source==='Juventus'?6:8,n=counts.get(p.source)||0;if(n>=max)return false;counts.set(p.source,n+1);return true})}
async function getSocial(){try{return await liveSocial()}catch{return []}}
export default async function SocialPage(){const social=await getSocial();return <main className="socialPage"><SocialRefresh/><header><div className="brandrow"><b>JUMP PRESS</b><a href="/news">← Indietro</a></div><small>NEWS</small><h1>Juventus <span>social</span></h1><p>Aggiornamenti X da fonti selezionate, filtrati sulla Juventus.</p><div className="tabs"><a href="/news">WEB</a><b>SOCIAL</b></div></header><section><SocialFeed livePosts={social}/></section><style>{`.socialPage{max-width:980px;margin:0 auto;padding:54px 24px 45px;font-family:Arial,Helvetica,sans-serif;color:#f4f4f4}.socialPage header{padding-bottom:18px}.brandrow{display:flex;justify-content:space-between;align-items:center;margin-bottom:40px}.brandrow>b{font-size:20px;letter-spacing:2px}.brandrow a,.tabs a{color:#fff;text-decoration:none;border:1px solid #555;border-radius:999px;padding:11px 18px;font-weight:800}.socialPage small{color:#dfff2f;letter-spacing:2px;font-weight:900}.socialPage h1{font-size:64px;line-height:.95;margin:18px 0 24px;letter-spacing:-2.5px}.socialPage h1 span{color:#d6d6d6}.socialPage header>p{font-size:18px;line-height:1.55;color:#ddd;max-width:650px}.tabs{display:flex;gap:12px;margin-top:25px}.tabs a,.tabs b{padding:12px 28px}.tabs b{background:#dfff2f;color:#111;border-radius:999px}.socialPage section{background:#11161a;border:1px solid #2d3338;border-radius:24px;padding:16px;margin-top:26px}.feedstatus{display:inline-block;margin:0 0 14px;padding:9px 12px;border:1px solid #384047;border-radius:999px;color:#cfd2d3;font-size:12.5px}.post{display:block;padding:20px;margin-bottom:12px;background:#171c20;border:1px solid #343a40;border-radius:18px;color:#f5f5f5;text-decoration:none}.post:last-child{margin-bottom:0}.meta{display:flex;justify-content:space-between;gap:14px;font-size:13px;color:#aeb3b7}.meta b{color:#fff}.post p{font-size:16px;line-height:1.48;margin:13px 0}.post strong{font-size:13px;color:#dfff2f}.empty{padding:26px;background:#171c20;border:1px solid #343a40;border-radius:18px}.empty b{font-size:22px}.empty p{color:#b8bdc1;line-height:1.5}@media(max-width:600px){.socialPage{padding:42px 18px 32px}.brandrow{margin-bottom:32px}.socialPage h1{font-size:52px;letter-spacing:-2px}.socialPage header>p{font-size:17px}.socialPage section{margin-left:-4px;margin-right:-4px;padding:10px;border-radius:20px}.post{padding:17px 16px;border-radius:16px}.post p{font-size:15.5px}.meta{font-size:12.5px}.tabs a,.tabs b{padding:11px 24px}}`}</style></main>}
