import {unstable_cache} from 'next/cache';
import SocialRefresh from './SocialRefresh';
import SocialFeed from './SocialFeed';

export const dynamic='force-dynamic';
const SOCIAL_MAX_AGE=3*24*60*60*1000;
const SOCIAL_SOURCES=[
 {name:'Juventus',handle:'juventusfc',official:true},{name:'Gianluca Di Marzio',handle:'DiMarzio'},
 {name:'Fabrizio Romano',handle:'FabrizioRomano'},{name:'Nicolò Schira',handle:'NicoSchira'},
 {name:'Gianluigi Longari',handle:'Glongari'},{name:'Romeo Agresti',handle:'romeoagresti'},
 {name:'TUTTOmercatoWEB',handle:'TuttoMercatoWeb'},{name:'Cronache di Spogliatoio',handle:'CronacheTweet'},
 {name:'Corriere dello Sport',handle:'CorSport'},{name:'Sport Mediaset',handle:'sportmediaset'},
 {name:'Sky Sport',handle:'SkySport'},{name:'ilBiancoNero',handle:'ilbianconerocom'},
 {name:'Fanpage.it',handle:'fanpage'},{name:'Calcio Totale',handle:'calcio_morelli'},
 {name:'Calcio e Finanza',handle:'CalcioFinanza',allPosts:true},{name:'Paolo Ardoino',handle:'paoloardoino',ardoino:true}
];
function relevantToJuve(body='',s={}){return /\b(juventus|juve|bianconer\w*|allianz\s*stadium|spalletti|yildiz|miretti|bremer|thuram|koopmeiners|cambiaso|vicario|di\s*gregorio|chiellini|comolli|kessi[eé]|sorloth|zirkzee|kolo\s*muani|david|muharemovi[cć]|martinez)\b/i.test(body)||Boolean(s.ardoino&&/\b(zebra|zebre|jay)\b/i.test(body));}
function cleanMarkdown(s=''){return s.replace(/\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)/g,' ').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\\([#_*`])/g,'$1').replace(/## Log in or sign up for X[\s\S]*$/i,'').replace(/## See .*?full profile[\s\S]*$/i,'').replace(/\s+/g,' ').replace(/(?:\s+\d+(?:\.\d+)?[KMB]?){2,8}\s*$/i,'').trim();}
function relativeDate(label=''){const now=Date.now();let m=label.match(/^(\d+)(s|m|h|d)$/i);if(m){const mult={s:1000,m:60000,h:3600000,d:86400000}[m[2].toLowerCase()];return new Date(now-Number(m[1])*mult)}m=label.match(/^([A-Z][a-z]{2})\s+(\d{1,2})(?:,\s*(\d{4}))?$/);if(m){const y=m[3]?Number(m[3]):new Date().getUTCFullYear();const d=new Date(`${m[1]} ${m[2]}, ${y} 12:00:00 UTC`);if(!Number.isNaN(d.getTime()))return d}return new Date(0)}
function parseJinaX(text,s){const posts=[];for(const block of text.split(/\n(?=\*\s+)/g)){const re=new RegExp(`\\[([^\\]]+)\\]\\(https:\\/\\/x\\.com\\/${s.handle}\\/status\\/(\\d+)\\)`,'i');const hit=block.match(re);if(!hit)continue;const label=hit[1].trim();if(!/^(?:\d+[smhd]|[A-Z][a-z]{2}\s+\d{1,2}(?:,\s*\d{4})?)$/i.test(label))continue;const body=cleanMarkdown(block.slice((hit.index||0)+hit[0].length));const d=relativeDate(label),ts=d.getTime();if(!body||!ts||!(s.official||s.allPosts||relevantToJuve(body,s)))continue;posts.push({source:s.name,body,date:d.toISOString(),ts,link:`https://x.com/${s.handle}/status/${hit[2]}`})}return posts}
async function fetchJinaX(handle){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(`https://r.jina.ai/https://x.com/${handle}`,{cache:'no-store',signal:c.signal,headers:{Accept:'text/plain','User-Agent':'Mozilla/5.0'}});if(!r.ok)throw new Error(String(r.status));const text=await r.text();if(!/status\//i.test(text))throw new Error('empty');return text}finally{clearTimeout(t)}}
const cached=unstable_cache(async h=>fetchJinaX(h),['jump-social-x-last-good-v4'],{revalidate:120});
async function one(s){try{return parseJinaX(await cached(s.handle),s).slice(0,s.allPosts?20:8)}catch{return []}}
function dedupe(a){const seen=new Set();return a.sort((x,y)=>y.ts-x.ts).filter(p=>{if(seen.has(p.link))return false;seen.add(p.link);return true})}
async function liveSocial(){const settled=await Promise.allSettled(SOCIAL_SOURCES.map(one));const cutoff=Date.now()-SOCIAL_MAX_AGE,counts=new Map();return dedupe(settled.flatMap(r=>r.status==='fulfilled'?r.value:[])).filter(p=>p.ts>=cutoff).filter(p=>{const max=p.source==='Calcio e Finanza'?20:p.source==='Juventus'?5:7,n=counts.get(p.source)||0;if(n>=max)return false;counts.set(p.source,n+1);return true})}
async function getSocial(){try{return await liveSocial()}catch{return []}}
export default async function SocialPage(){const social=await getSocial();return <main className="socialPage"><SocialRefresh/><header><div className="brandrow"><b>JUMP PRESS</b><a href="/news">← Indietro</a></div><small>NEWS</small><h1>Juventus <span>social</span></h1><p>Aggiornamenti X da fonti selezionate, filtrati sulla Juventus.</p><div className="tabs"><a href="/news">WEB</a><b>SOCIAL</b></div></header><section><SocialFeed livePosts={social}/></section><style>{`
.socialPage{max-width:980px;margin:0 auto;padding:54px 24px 45px;font-family:Arial,Helvetica,sans-serif;color:#f4f4f4}.socialPage header{padding-bottom:18px}.brandrow{display:flex;justify-content:space-between;align-items:center;margin-bottom:40px}.brandrow>b{font-size:20px;letter-spacing:2px}.brandrow a,.tabs a{color:#fff;text-decoration:none;border:1px solid #555;border-radius:999px;padding:11px 18px;font-weight:800}.socialPage small{color:#dfff2f;letter-spacing:2px;font-weight:900}.socialPage h1{font-size:64px;line-height:.95;margin:18px 0 24px;letter-spacing:-2.5px}.socialPage h1 span{color:#d6d6d6}.socialPage header>p{font-size:18px;line-height:1.55;color:#ddd;max-width:650px}.tabs{display:flex;gap:12px;margin-top:25px}.tabs a,.tabs b{padding:12px 28px}.tabs b{background:#dfff2f;color:#111;border-radius:999px}.socialPage section{background:#11161a;border:1px solid #2d3338;border-radius:24px;padding:16px;margin-top:26px}.feedstatus{display:inline-block;margin:0 0 14px;padding:9px 12px;border:1px solid #384047;border-radius:999px;color:#cfd2d3;font-size:12.5px}.feedstatus::first-letter{color:#dfff2f}.post{display:block;padding:20px;margin-bottom:12px;background:#171c20;border:1px solid #343a40;border-radius:18px;color:#f5f5f5;text-decoration:none}.post:last-child{margin-bottom:0}.meta{display:flex;justify-content:space-between;gap:14px;font-size:13px;color:#aeb3b7}.meta b{color:#fff}.post p{font-size:16px;line-height:1.48;margin:13px 0}.post strong{font-size:13px;color:#dfff2f}.empty{padding:26px;background:#171c20;border:1px solid #343a40;border-radius:18px}.empty b{font-size:22px}.empty p{color:#b8bdc1;line-height:1.5}@media(max-width:600px){.socialPage{padding:42px 18px 32px}.brandrow{margin-bottom:32px}.socialPage h1{font-size:52px;letter-spacing:-2px}.socialPage header>p{font-size:17px}.socialPage section{margin-left:-4px;margin-right:-4px;padding:10px;border-radius:20px}.post{padding:17px 16px;border-radius:16px}.post p{font-size:15.5px}.meta{font-size:12.5px}.tabs a,.tabs b{padding:11px 24px}}
`}</style></main>}
